server:
  port: 8040

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: curso-service
          uri: lb://curso-service
          predicates:
            - Path=/cursos/**
